GestStore/Controllers/ClientController.cs
using AutoMapper;
using GestStore.Models;
using GestStore.Persistence;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using AspNetCoreHero.ToastNotification.Abstractions;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GestStore.Controllers
{
    public class ClientController : Controller
    {
        private readonly ILogger<ClientController> _logger;
        private readonly ApplicationDbContext _dbContext;
        private readonly IMapper _mapper;
        private readonly INotyfService _notifyService;
        public ClientController(ILogger<ClientController> logger, ApplicationDbContext dbContext, IMapper mapper,
            INotyfService notifyService)
        {
            _logger = logger;
            _dbContext = dbContext;
            _mapper = mapper;
            _notifyService = notifyService;
        }
       
        public IActionResult Index()
        {
            var clients = _dbContext.Clients.ToList();
            var viewModels = new List<ClientViewModel>();
            foreach (var client in _dbContext.Clients)
               viewModels.Add(_mapper.Map<ClientViewModel> (client));

                return View(viewModels);
        }
        public IActionResult Create()
        {
            return RedirectToAction("Edit");
        }
        public IActionResult Edit()
        {
            return View();
        }
        

        [HttpPost]
        public ActionResult SaveClient(ClientViewModel item)
        {
            _logger.LogTrace($"Received model with ID {item.ClientID}");
            var client = new ClientViewModel()
            {
                ClientID = item.ClientID,
                Nom = item.Nom,
                Prenom = item.Prenom,
                Cp = item.Cp,
                Localite = item.Localite,
                Rue = item.Rue,
                Numero = item.Numero,
                Tel = item.Tel
            };
            _dbContext.Add(client);
            _dbContext.SaveChanges();

            
            return RedirectToAction("Index");
        }
    }
}

GestStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GestStore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">GestStore</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li>
                            <a class="nav-link text-dark" asp-area="" asp-controller="Client" asp-action="Index"> Customer Management</a>
                        </li>
                        <li>
                            <a class="nav-link text-dark" asp-area="" asp-controller="ComFact" asp-action="Index"> Bill Management</a>
                        </li>
                        <li>
                            <a class="nav-link text-dark" asp-area="" asp-controller="Produit" asp-action="Index"> Product Management</a>
                        </li>
                    </ul>
                </div>

                <div id="loading" style="display: none">
                    <div class="spinner-border spinner-border-sm" role="status">
                        <span class="sr-only">Loading...</span>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - GestStore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    @await Html.PartialAsync("_ValidationScriptsPartial")
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>